.TH ccut 1 ccut\-0.0.1
.SH USAGE
.B ccut f1,f2,f3... [FILE]
.SH OPTIONS
.B f1,f2,f3...
Process fields 
.B f1,f2,f3... 
etc
.B f1 
etc may be ranges,
eg: 
.B 3,6\-9,15,2
.br
.B 0 
is a special blank field
.br
Numbers may be given with override header and filler
like so:
.LP
.B N:header:filler
.br
.B N:header:
.br
.B N::filler
.LP
.B \-h
Display help and exit.
.br
.B \-8
Use utf-8 for input and output
.br
.SH EXAMPLES
.B ccut 4,3 ORDERS.csv > NEWORDERS.csv
Put the fourth and then third column of 
.B ORDERS
in 
.B NEWORDERS.
.SH SEE ALSO
.B chead(1) cjoin(1) cval(1)
.SH BUGS
Fields are numbered from 1 on the command line,
but internally
are represented from 0.
Probably others.
