.TH chead 1 chead\-0.0.1
.B chead \- display field headers for a csv file
.SH USAGE
.B chead [\-u] FILE
.br
.B chead [\-u] {FIELD} {FIELD}... {FILE}
.br
.B chead \-i [\-u] {FIELD} {FIELD}... {FILE}
.br
.B chead \-h
.br
In the first form,
.B chead
will display all field headers,
numbered one
per line,
for FILE.
In the second form,
.B chead
will output the matching field headers as
a comma\-separated list of numbers,
suitable for use as a flag for ccut,
cdel,
etc.
The third form is the inverse of the second form \- it outputs the 
field headers that do not match.
.SH OPTIONS 
.B \-h
Display help and exit.
.br
.B \-i
Invert the matching of field headers.
.br
.B \-u
Use unix line endings for input and output
.br
.SH EXAMPLES
.SH SEE ALSO
ccut
.B chead
cjoin
csort
cval
.SH BUGS
Don't use this with Strawberry Perl.
If you are on Windows,
use Cygwin Perl.
(Not tested with ActiveState Perl.)
Fields are numbered from 1 on the command line,
but internally
are represented from 0.
Assumes all csvs use /r/n as EOL.
.SH TODO
Does the file exist? Did we receive garbage flags?
