.TH chead 1 chead\-0.0.1
.B chead \- display field headers for a csv file
.SH USAGE
.B chead FILE
.br
.B chead {FIELD} {FIELD}... {FILE}
.br
.B chead \-i {FIELD} {FIELD}... {FILE}
.br
.B chead \-h
.br
In the first form,
.B chead
will display all field headers,
numbered one
per line,
for 
.B FILE.
In the second form,
.B chead
will output the matching field headers as
a comma\-separated list of numbers,
suitable for use as a flag for 
.B ccut.
The third form is the inverse of the second form \(em it outputs the 
field headers that do not match.
.SH OPTIONS 
.B \-h
Display help and exit.
.br
.B \-i
Invert the matching of field headers.
.br
.B \-w
use dos / windows style newlines for input.
.br
.B \-8
Force utf-8 encoding of input
.br
.SH EXAMPLES
.SH SEE ALSO
.B ccut(1) cjoin(1) cval(1)
.SH BUGS
Fields are numbered from 1 on the command line,
but internally
are represented from 0.
Probably others.
