.TH cjoin 1 cjoin\-0.0.1
.SH USAGE
.B cjoin [\-s S] \-1 FIRSTFIELD \-2 SECONDFIELD file1 file2
.br
.B cjoin [\-s S] \-j JOINTFIELD file1 file2
.br
.B cjoin \-h
.SH OPTIONS
.B \-s
S           Print but do not process first S lines
.br
.B \-j
FIELD       Join on FIELD of both files
.br
.B \-1
FIELD       Join on FIELD of file one
.br
.B \-2
FIELD       Join on FIELD of file two
.br
.B \-h
Display help and exit
.br
.B \-w
use dos / windows style newlines for input.
.br
.B \-W
use dos / windows style newlines for output.
.br
.SH EXAMPLES
.B cjoin \-s1 \-1 1 \-2 3 ORIGINAL.csv X\-REF.csv 
Print all lines of 
.B XREF 
where field 3 matches 
.B ORIGINAL
field 1.
Also print the first line,
no matter what.
.SH SEE ALSO
.B ccut(1) chead(1) cval(1)
.SH BUGS
Fields are numbered from 1 on the command line,
but internally
are represented from 0.
Probably others.
