#!/usr/bin/perl
use strict;
use warnings;
use vars qw($opt_D $opt_d $opt_h $opt_Q $opt_q $opt_s $opt_v);
use Getopt::Std;
use Text::CSV;

my ($silent, $verbose, $nf, $of);

my $error = 0;

my $outdelim = ',';
my $outquote = '"';

my @rows;
my $lines = 0;
my $csvin  = Text::CSV->new ({ binary => 1, eol => $/ });
my $csvout = Text::CSV->new ({ binary => 1, eol => $/, always_quote =>1 });

getopts('D:d:hq:Q:suv');
if ($opt_d) { $csvout->sep_char ($opt_D); }
if ($opt_d) { $csvin->sep_char ($opt_d); }
if ($opt_h) { &help(0); }
if ($opt_q) { $csvout->quote_char ($opt_Q); }
if ($opt_q) { $csvin->quote_char ($opt_q); }
if ($opt_s) { $silent = 1; }
if ($opt_v) { $verbose = 1; }

my $stdout;
open $stdout, ">-:encoding(utf8)" or die "Can't open standard out: $!";

@ARGV = ("-") unless @ARGV;
while (@ARGV) {
    my $fh;
    $ARGV= shift @ARGV;
    if ($ARGV eq '-') {
        $fh = *STDIN;
        open $fh, "<-:encoding(utf8)" or die "Can't open standard in: $!";
    } else {
        open $fh, "<:encoding(utf8)", $ARGV or die "Can't open $ARGV: $!";
    }

    LINE: while (my $row = $csvin->getline ( $fh )) {
        $lines++;
        my @fields = @$row;
        $nf = $#fields + 1;

        if ($lines == 1) {
            $of = $nf;
        }
        if ($nf != $of) {
            warn "LINE: $. of $ARGV\t$nf fields, $of in previous line\n";
            $error = 1;
        }
        $of = $nf;
        if ($verbose) {
            $csvout->print ($stdout, $row);
        }
    }
}

if (!$silent && !$error) {
    warn "$lines lines of $of columns each.\n";
}

exit $error;

sub help {
    my $status = shift;
    while (<DATA>) { print; }
    exit $status;
}

__END__

USAGE
cval -h
cval [-q] [FILE]
cval -v [-DOPTION] [-QOPTION] [FILE]

OPTIONS
-h  Display help and exit. 
-D  specify an output delimiter other than ","
-d  specify an input delimiter other than ","
-Q  specify an output quote character other than '"'
-q  specify an input quote character other than '"'
-s  Don't print messages, just return 0 for good and 1 for bad.
-v  (verbose) print the lines as they are validated.

EXAMPLES
  cval FILE 
Check a csv for well-formedness, displaying commentary as we go
  cval -v -s FILE 
Essentially, cat FILE, "normalizing" quotes,  and return 0 if it was good.
  cval -v -D'|' -Q'^' FILE
convert a csv to summation style
  cval -v -D$(printf '\024') -Q$(printf '\376') FILE
convert a csv to a concordance .dat 

SEE ALSO
ccut
chead
cjoin
csort

BUGS
Don't use this with Strawberry Perl. If you are on Windows,
use Cygwin Perl. (Not tested with ActiveState Perl.)
Only reads from "sample.csv" in current directory.
-D and -Q flags broken, at least for dat style files

TODO
Check our arguments better - 
Does the file exist? Did we receive garbage flags?
