.TH cval 1 cval\-0.0.1
.SH USAGE
.B cval \-h
.br
.B cval [\-u] [\-q] [FILE]
.br
.B cval [\-u] \-v [\-dOPTION] [\-QOPTION] [FILE]
.SH OPTIONS
.B \-d
specify an output delimiter other than ","
.br
.B \-h
Display help and exit.
.br
.B \-q
Don't print messages,
just return 0 for good and 1 for bad.
.br
.B \-Q
specify an output quote character other than '"'
.br
.B \-u
Use unix line endings for input and output
.br
.B \-v
(verbose) print the lines as they are validated.
.br
.SH EXAMPLES
.B cval FILE 
Check a csv for well\-formedness,
displaying commentary as we go
.B cval \-v \-q FILE 
Essentially,
cat 
.B FILE,
"normalizing" quotes,
and return 0 if it was good.
.B cval \-v \-d'|' \-Q'^' FILE
convert a csv to summation style
.B cval \-v \-d$(printf '\024') \-Q$(printf '\376') FILE
convert a csv to a concordance .dat 
.SH SEE ALSO
.B ccut(1) chead(1) cjoin(1)
.SH BUGS
Fields are numbered from 1 on the command line,
but internally
are represented from 0.
Probably others.
